pipeline {
   environment {
        PATH = "/opt/homebrew/bin"
    }
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
